class ValidationError(Exception):
    """Виняток, що генерується у разі помилки валідації даних."""
    pass
